# 注意!!!,本地开发时,请创建application-local.yml文件进行配置,不要随意修改application-default.yml文件并提交到git.

# 数据库相关配置
DB_HOST: 192.168.1.155 # postgresql/mysql 数据库地址
DB_PORT: 3306 # postgresql/mysql 数据库端口
DB_DATABASE: jetlinks # postgresql/mysql 数据库名
DB_USERNAME: root # postgresql/mysql 数据库用户名
DB_PASSWORD: Cst123456* # postgresql/mysql 数据库密码
DB_SCHEMA: jetlinks # postgresql 数据库schema,默认public, mysql时则为数据库名.(注意大小写,请勿使用-等特殊字符)
DB_DIALECT: mysql # 数据库方言,默认postgres. 支持postgres,mysql,oracle,sqlserver等.
# redis 相关配置
REDIS_HOST: 192.168.1.146
REDIS_PORT: 6379 # redis 数据库地址
REDIS_PASSWORD: "cstredis" # redis 密码
REDIS_DATABASE: 14 # redis 数据库索引

# postgresql—timescalbedb相关配置，
POSTGRESQL_HOST: 192.168.1.155 #  postgresql 数据库地址
POSTGRESQL_PORT: 5432 # postgresql 数据库端口
POSTGRESQL_DATABASE: jetlinks # postgresql 数据库schema
POSTGRESQL_USERNAME: postgres # postgresql 数据库用户名
POSTGRESQL_PASSWORD: root # postgresql/mysql 数据库密码
TIMESCALEDB_SCHEMA: timescaledb-device-data # timescaledb 数据库schema,默认public

# elasticsearch相关配置
ES_URIS: 192.168.1.155:9200
ES_USERNAME: "" # elasticsearch 用户名
ES_PASSWORD: "" # elasticsearch 密码

# rabbitmq相关配置
RABBITMQ_HOST: 192.168.1.159
RABBITMQ_PORT: 5672
RABBITMQ_USER_NAME: admin
RABBITMQ_PASSWORD: admin
